# Generated by Django 2.0.9 on 2018-10-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=4095),
        ),
    ]
